import type { LucideIcon } from 'lucide-react'
import {
  BabyIcon,
  BanknoteIcon,
  BathIcon,
  BikeIcon,
  BookOpenIcon,
  BriefcaseIcon,
  Building2Icon,
  BusIcon,
  CameraIcon,
  CarIcon,
  CatIcon,
  ClapperboardIcon,
  CoffeeIcon,
  CreditCardIcon,
  DogIcon,
  DropletsIcon,
  DumbbellIcon,
  FilmIcon,
  Flower2Icon,
  FuelIcon,
  Gamepad2Icon,
  GiftIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HeadphonesIcon,
  HeartPulseIcon,
  HotelIcon,
  HouseIcon,
  KeyRoundIcon,
  LandmarkIcon,
  LaptopIcon,
  LightbulbIcon,
  MapPinIcon,
  MonitorIcon,
  MusicIcon,
  PackageIcon,
  PawPrintIcon,
  PhoneIcon,
  PiggyBankIcon,
  PillIcon,
  PizzaIcon,
  PlaneIcon,
  PlugIcon,
  ReceiptIcon,
  RepeatIcon,
  SchoolIcon,
  ScissorsIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SofaIcon,
  SparklesIcon,
  StethoscopeIcon,
  TicketIcon,
  TrainFrontIcon,
  TruckIcon,
  TvIcon,
  UsersIcon,
  UtensilsIcon,
  WalletIcon,
  WifiIcon,
  WineIcon,
  WrenchIcon,
  ZapIcon,
} from 'lucide-react'

export const CATEGORY_ICON_KEYS = [
  'utensils',
  'pizza',
  'coffee',
  'wine',
  'car',
  'bus',
  'train',
  'bike',
  'fuel',
  'plane',
  'house',
  'sofa',
  'bath',
  'building',
  'hotel',
  'shoppingBag',
  'shoppingCart',
  'package',
  'gift',
  'shirt',
  'heartPulse',
  'stethoscope',
  'pill',
  'dumbbell',
  'clapperboard',
  'film',
  'ticket',
  'music',
  'gamepad',
  'tv',
  'headphones',
  'camera',
  'wallet',
  'banknote',
  'creditCard',
  'piggyBank',
  'handCoins',
  'landmark',
  'briefcase',
  'repeat',
  'receipt',
  'laptop',
  'smartphone',
  'monitor',
  'wifi',
  'zap',
  'plug',
  'lightbulb',
  'droplets',
  'wrench',
  'key',
  'book',
  'school',
  'graduation',
  'users',
  'baby',
  'dog',
  'cat',
  'paw',
  'flower',
  'sparkles',
  'scissors',
  'mapPin',
  'phone',
  'truck',
] as const

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number]

export const CATEGORY_ICONS: Record<CategoryIconKey, LucideIcon> = {
  utensils: UtensilsIcon,
  pizza: PizzaIcon,
  coffee: CoffeeIcon,
  wine: WineIcon,
  car: CarIcon,
  bus: BusIcon,
  train: TrainFrontIcon,
  bike: BikeIcon,
  fuel: FuelIcon,
  plane: PlaneIcon,
  house: HouseIcon,
  sofa: SofaIcon,
  bath: BathIcon,
  building: Building2Icon,
  hotel: HotelIcon,
  shoppingBag: ShoppingBagIcon,
  shoppingCart: ShoppingCartIcon,
  package: PackageIcon,
  gift: GiftIcon,
  shirt: ShirtIcon,
  heartPulse: HeartPulseIcon,
  stethoscope: StethoscopeIcon,
  pill: PillIcon,
  dumbbell: DumbbellIcon,
  clapperboard: ClapperboardIcon,
  film: FilmIcon,
  ticket: TicketIcon,
  music: MusicIcon,
  gamepad: Gamepad2Icon,
  tv: TvIcon,
  headphones: HeadphonesIcon,
  camera: CameraIcon,
  wallet: WalletIcon,
  banknote: BanknoteIcon,
  creditCard: CreditCardIcon,
  piggyBank: PiggyBankIcon,
  handCoins: HandCoinsIcon,
  landmark: LandmarkIcon,
  briefcase: BriefcaseIcon,
  repeat: RepeatIcon,
  receipt: ReceiptIcon,
  laptop: LaptopIcon,
  smartphone: SmartphoneIcon,
  monitor: MonitorIcon,
  wifi: WifiIcon,
  zap: ZapIcon,
  plug: PlugIcon,
  lightbulb: LightbulbIcon,
  droplets: DropletsIcon,
  wrench: WrenchIcon,
  key: KeyRoundIcon,
  book: BookOpenIcon,
  school: SchoolIcon,
  graduation: GraduationCapIcon,
  users: UsersIcon,
  baby: BabyIcon,
  dog: DogIcon,
  cat: CatIcon,
  paw: PawPrintIcon,
  flower: Flower2Icon,
  sparkles: SparklesIcon,
  scissors: ScissorsIcon,
  mapPin: MapPinIcon,
  phone: PhoneIcon,
  truck: TruckIcon,
}

export function getCategoryIcon(icon: string): LucideIcon {
  if (icon in CATEGORY_ICONS) {
    return CATEGORY_ICONS[icon as CategoryIconKey]
  }

  return WalletIcon
}

export const DEFAULT_CATEGORY_COLOR = '#3f3f46'
